### ISSUE TITLE
Basic landing page

### ISSUE THREAD

**Issue by rngadam** [coderbunker/coderbunker.ca#1]
Need basic landing page so we can switch to a country selector (https://github.com/coderbunker/coderbunker.com/issues/1)

* [x] history and context
* [x] logo present
* [x] address present
* [x] generic email contact present (ca@coderbunker.com)
* [x] social network (LinkedIn)
* [x] team (Jérémy, Élic, Ricky) with LinkedIn and Github links
* [x] list of services
* [x] list of partners (TechnoLibre, Drave Développement, Diginov and Why Not Blue)
* [x] French version

**Comment by Carms-dev** [comment]
- [ ]  validate page
- [ ]  document the deployment steps and structure of code
- [ ]  deploy to coderbunker.ca (access to Google Domains)
- [ ]  set up deployment from main and staging
- [ ]  FR translation
- [ ] Add the remaining profile & picture & profile
- [ ] Replace the placeholder pdf when the Retainer Agreement PDF is ready
