### ISSUE TITLE
The arrow

### ISSUE THREAD

**Issue by karenz02** [coderbunker/coderbunker.ca#24]
The arrow to consult the profile aren't visible on screen, can't scroll from left to right. @Carms-dev 

![Profil](https://user-images.githubusercontent.com/86493252/125981689-378120e3-9760-4406-9b07-5238068c3031.jpg)

**Comment by Carms-dev** [comment]
I'm closing this issue, given the avatar is linked to the corresponding profile with smooth scroll as per your specification.  Please open a new issue when you remember what about the arrow!
