### ISSUE TITLE
Hidden

### ISSUE THREAD

**Issue by karenz02** [coderbunker/coderbunker.ca#25]
The sentence : Rejoignez notre communauté is hidden @Carms-dev 

![Camoufler](https://user-images.githubusercontent.com/86493252/125982051-3c4f3e31-490f-4677-a934-961ffc29d880.jpg)
 on the page.

**Comment by karenz02** [comment]
The same thing happen

![image](https://user-images.githubusercontent.com/86493252/131556571-ec7d1d1a-7d63-4194-be59-70585b188bb2.png)

**Comment by Carms-dev** [comment]
As discussed over email, this is resolved when you remove the "zoom in" in your browser.
