### ISSUE TITLE
Use <filename>.<language>.json instead of a singular locale file

### ISSUE THREAD

**Issue by rngadam** [coderbunker/coderbunker.ca#4]
There's too much of a disconnect between a single centralized translation file and the JSON document it translates.

It would be better to fetch base on language preference:

* team.en.json for English (default)
* team.fr.json for French

and keep both files in the same directory.

**Comment by Carms-dev** [comment]
@rngadam 

The `team.json` and `translation.json` files serve different purposes.  The former is the info on team members (in the `content` directory) and the later on translation strings (in the `locales` directory)

Given the difference in purposes, I think it'd make sense to keep them separate, though i hear you in terms of having one translation file will get messy quickly as the team grows, and it'd be nice to separate the team segment out from a centralised `translation.json` file.

I think the following could make sense.

```
├── locales 
│          ├── en
│          │      ├── index.json
│          │      └── team.json
│          └── fr
│                  ├── index.json
│                  └── team.json
├── src
     ├── assets
             ├── content
                      └── team.json
```

Let me know what you think!

**Comment by Carms-dev** [comment]
see [pull request #14](https://github.com/coderbunker/coderbunker.ca/pull/14)

& staged [here](https://coderbunker.github.io/coderbunker.ca/fr/)

**Comment by rngadam** [comment]
team.fr.json to match team.json
