### ISSUE TITLE
Replace the placeholder pdf with JotForm

### ISSUE THREAD

**Issue by rngadam** [coderbunker/coderbunker.ca#9]
Should be easy for visiting potential clients to self-serve the retainer agreement based on this:

https://docs.google.com/document/d/1eoEYLPZ52DlUBUkvddIcqBRvQXvjFitIjd_PBoyjrFE/edit

Visiting client should be able to fill in an HTML form, digitally sign and get a PDF that they can submit to us.

**Comment by rngadam** [comment]
let's use the jotform placeholder we created @Carms-dev

**Comment by Carms-dev** [comment]
Date fields added for contract start & end, which are reflected dynamically in the terms.

![Screenshot from 2021-05-13 12-28-54](https://user-images.githubusercontent.com/59268689/118156110-fc334300-b3e6-11eb-8ead-8633155b1398.png)
